#pragma once

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <UIKit/UIKit.h>

#import "AP_Font_Run.h"

// Replacement for UIFont.
// We do all layout and rendering ourselves, using tables generated by tools/fontex.cpp
@interface AP_Font : NSObject

+ (AP_Font*) fontWithName:(NSString*)fontName size:(CGFloat)fontSize;
+ (AP_Font*) systemFontOfSize:(CGFloat)fontSize;
+ (AP_Font*) boldSystemFontOfSize:(CGFloat)fontSize;
+ (AP_Font*) italicSystemFontOfSize:(CGFloat)fontSize;

@property(nonatomic,readonly) NSString* fontName;
@property(nonatomic,readonly) CGFloat pointSize;
@property(nonatomic,readonly) CGFloat ascender;
@property(nonatomic,readonly) CGFloat descender;
@property(nonatomic,readonly) CGFloat lineHeight;
@property(nonatomic,readonly) CGFloat leading;

- (AP_Font*) fontWithSize:(CGFloat)fontSize;

- (AP_Font_Run*) runForString:(NSString*)string;
- (AP_Font_Run*) runForChars:(unichar*)chars size:(size_t)size;

@end
