#import <Foundation/Foundation.h>

#ifdef AP_REPLACE_UI

#import "AP_Font_Run.h"

// Replacement for UIFont.
// We do all layout and rendering ourselves, using tables generated by tools/fontex.cpp
@interface AP_Font : NSObject

+ (AP_Font*) fontWithName:(NSString*)fontName size:(CGFloat)fontSize;

@property(nonatomic,readonly) NSString* fontName;
@property(nonatomic,readonly) CGFloat pointSize;
@property(nonatomic,readonly) CGFloat ascender;
@property(nonatomic,readonly) CGFloat descender;
@property(nonatomic,readonly) CGFloat lineHeight;
@property(nonatomic,readonly) CGFloat leading;

- (AP_Font*) fontWithSize:(CGFloat)fontSize;

- (AP_Font_Run*) runForString:(NSString*)string;
- (AP_Font_Run*) runForChars:(unichar*)chars size:(size_t)size;

@end

#else
typedef UIFont AP_Font;
#endif
